name = "bare_touch_panel"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[configuration.variables]
device = { type = "Enum", values = ["ft6x06", "ft5336", "stmpe811"], default = "ft5336" }

[[depends-on]]
bare_types = "0.1.0-dev"
bare_hal = "0.1.0-dev"